# Generated by Django 5.0.2 on 2024-02-19 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_post_subtitle"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="subtitle",
        ),
    ]
