# Generated by Django 5.0.2 on 2024-02-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="subtitle",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
