# Generated by Django 5.0.2 on 2024-03-15 01:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_alter_post_subtitle"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["originally_published"]},
        ),
    ]
